
export const DEVICE_INIT = "DEVICE_INIT"
export const DEVICE_WAITING = "DEVICE_WAITING"
export const DEVICE_CONNECTING = "DEVICE_CONNECTING"
export const DEVICE_CONNECTED = "DEVICE_CONNECTED"
export const DEVICE_DISCONNECTED = "DEVICE_DISCONNECTED"
