source 'https://github.com/CocoaPods/Specs.git'


platform :ios, '8.0'
project 'MoreDebug.xcodeproj'

#use_frameworks!

target 'MoreDebug' do

  pod 'DDMoreDebug', :path=>'..'
  pod 'SAMKeychain'

end
